### ISSUE TITLE
PRACTICA ARCHITECT MAVIEL MARTINEZ CHOLULA

### ISSUE THREAD

**Issue by MAB288** [SistemasTecTlaxiaco/actividad-3-practica-architect-MAB288#1]
[PRACTICA ARCHITECT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-MAB288/files/12554351/PRACTICA.ARCHITECT.pdf)

**Comment by Irvingzr16** [comment]
Portada: 25. Cumple con lo requerido
Procedimiento:20, El procedimiento está bien desarrollado
Figuras: 17.5.  Faltaron con algunas imágenes
Resultados y conclusiones: 19 Tiene conclusión, pero faltaron los resultados
_Puntos totales: 81.5_

**Calificación final: 16.5/ 20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
